server.port: 8080

stats-service.url: http://localhost:9090
ewm-stats-dto.timestamp-pattern: yyyy-MM-dd HH:mm:ss
ewm-service:
  app: ewm-main-service
  date-start-app: 2024-10-01 00:00:00
#ewm-service.executor-max-pool-size:

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
    #show-sql: true
  sql.init.mode: always
  #config.activate.on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: ewm
    password: ewm
  h2.console.enabled: true

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type: INFO
      orm.jdbc.bind: TRACE