
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(254) NOT NULL,
  name VARCHAR(250) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS location_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_location_type PRIMARY KEY (id),
  CONSTRAINT uq_location_type_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL,
  confirmed_requests INT NOT NULL,
  created_on TIMESTAMP NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  user_id BIGINT NOT NULL,
  location_lat FLOAT NOT NULL,
  location_lon FLOAT NOT NULL,
  location_type_id BIGINT,
  location_name VARCHAR(50),
  paid BOOLEAN NOT NULL,
  participant_limit INT NOT NULL,
  published_on TIMESTAMP,
  request_moderation BOOLEAN NOT NULL,
  state VARCHAR(16) NOT NULL,
  title VARCHAR(120) NOT NULL,
  views BIGINT,
  CONSTRAINT pk_event PRIMARY KEY (id),
  CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id),
  CONSTRAINT fk_events_to_users FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINT fk_events_to_location_types FOREIGN KEY(location_type_id) REFERENCES location_types(id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created TIMESTAMP NOT NULL,
  event_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT fk_requests_to_events FOREIGN KEY(event_id) REFERENCES events(id),
  CONSTRAINT fk_requests_to_users FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINT uq_user_id_event_id UNIQUE (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN NOT NULL,
  title VARCHAR(50) NOT NULL,
  CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  compilation_id BIGINT NOT NULL,
  event_id BIGINT,
  CONSTRAINT pk_compilation_event PRIMARY KEY (id),
  CONSTRAINT fk_to_compilations FOREIGN KEY(compilation_id) REFERENCES compilations(id),
  CONSTRAINT fk_to_events FOREIGN KEY(event_id) REFERENCES events(id)
);

CREATE OR REPLACE FUNCTION distance(lat1 float, lon1 float, lat2 float, lon2 float)
    RETURNS float AS '
    declare
        dist float = 0;
        rad_lat1 float;
        rad_lat2 float;
        theta float;
        rad_theta float;
    BEGIN
        IF lat1 = lat2 AND lon1 = lon2
        THEN
            RETURN dist;
        ELSE
            -- переводим градусы широты в радианы
            rad_lat1 = pi() * lat1 / 180;
            -- переводим градусы долготы в радианы
            rad_lat2 = pi() * lat2 / 180;
            -- находим разность долгот
            theta = lon1 - lon2;
            -- переводим градусы в радианы
            rad_theta = pi() * theta / 180;
            -- находим длину ортодромии
            dist = sin(rad_lat1) * sin(rad_lat2) + cos(rad_lat1) * cos(rad_lat2) * cos(rad_theta);

            IF dist > 1
                THEN dist = 1;
            END IF;

            dist = acos(dist);
            -- переводим радианы в градусы
            dist = dist * 180 / pi();
            -- переводим градусы в километры
            dist = dist * 60 * 1.8524;

            RETURN dist;
        END IF;
    END;
' LANGUAGE PLPGSQL;

/*
CREATE ALIAS distance AS '
    Double distance(Double lat, Double lon, Double locationLat, Double locationLon) {
        double rad_lat1 = lat * Math.PI / 180;
        double rad_lat2 = locationLat * Math.PI / 180;
        double rad_lon1 = lon * Math.PI / 180;
        double rad_lon2 = locationLon * Math.PI / 180;

        if (rad_lat1 > rad_lat2) {
            if (rad_lon1 > rad_lon2) {
                return calculateDistance(rad_lat1, rad_lat2, rad_lon1, rad_lon2);
            } else {
                return calculateDistance(rad_lat2, rad_lat1, rad_lon1, rad_lon2);
            }
        } else {
            if (rad_lon1 > rad_lon2) {
                return calculateDistance(rad_lat1, rad_lat2, rad_lon2, rad_lon1);
            } else {
                return calculateDistance(rad_lat2, rad_lat1, rad_lon2, rad_lon1);
            }
        }
    }

    static Double calculateDistance(double latMax, double latMin, double lonMax, double lonMin) {
        double radius = 6371;
        double deltaLat = 2 * radius * Math.sin((latMax - latMin) / 2);
        double deltaLonMin = 2 * radius * Math.cos(latMax) * Math.sin((lonMax - lonMin) / 2);
        double deltaLonMax = 2 * radius * Math.cos(latMin) * Math.sin((lonMax - lonMin) / 2);
        double deferenceDeltaLon = (deltaLonMax - deltaLonMin) / 2;
        double lengthBetweenLatSqrt = Math.pow(deltaLat, 2) - Math.pow(deferenceDeltaLon, 2);
        double length = Math.sqrt(lengthBetweenLatSqrt + Math.pow(deltaLonMax - deferenceDeltaLon, 2));
        double alfa = 2 * Math.asin(length / (2 * radius));
        return alfa * radius;
    }
';
*/