services:
  stats-service:
    build: stats/stats-service
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=ewm-stats
      - SPRING_DATASOURCE_PASSWORD=ewm-stats
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=ewm-stats
      - POSTGRES_USER=ewm-stats
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-service
#      - ewm-db
    environment:
      - STATS_SERVICE_URL=http://stats-service:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
#      - SPRING_DATASOURCE_USERNAME=ewm
#      - SPRING_DATASOURCE_PASSWORD=ewm
#      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
#
#  ewm-db:
#    image: postgres:16.1
